In [1]:
import numpy as np
x = np.array([1,2,3,4,5])

In [2]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Save a numpy matrix to disk, and load it into another variable and compare them

In [3]:
np.save('saved_numpy_array', x)


In [4]:
y = np.load('saved_numpy_array.npy')
print('y = ', y)
print('x == y', x == y)


y =  [1 2 3 4 5]
x == y [ True  True  True  True  True]


Create matrices with filled with 1's or filled with any number.

In [5]:
z = np.ones((4,5))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
X = np.zeros((3,4))
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
a = np.full((4,5), 5)
print(a)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


Check the type of a

In [8]:
print(a.dtype)

int64


Create an identiy matrix, then create a zero filled matrix with the diagonal set to values.

In [10]:
b = np.eye(5)
print(b)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [11]:
c = np.diag([10,20,30,50])
print(c)


[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


Create a 1-dimensional array with evenly spaced intervals: with arguements start, stop and interval.
* range with stop (exclusive)
* range with start (inclusive) and stop (exclusive)
* range with start stop and step

In [18]:
d = np.arange(10)
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
d = np.arange(4, 10)
print(d)

[4 5 6 7 8 9]


In [19]:
d = np.arange(1, 14, 3)
print(d)

[ 1  4  7 10 13]


To use non-integer steps can create inconsistencies due to finite floating-point percision. For non-intersteps, use linspace.
* start/stop required and inclusive
* is the number of points returned

In [20]:
d = np.linspace(0, 25, 10)
print(d)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


We can exclude the last value (in this case 25) and it will find 10 points between 0 without including 25 - basically creates an eqivalance class or congruency. Example:

In [21]:
d = np.linspace(0, 25, 10, endpoint=False)
print(d)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [22]:
d = np.linspace(0, 25, 10, endpoint=False).reshape(5,2)
print(d)

[[ 0.   2.5]
 [ 5.   7.5]
 [10.  12.5]
 [15.  17.5]
 [20.  22.5]]


In [23]:
d = np.arange(20).reshape(10, 2)
print(d)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [24]:
d = np.random.random((3,3))
print(d)

[[0.83262043 0.45454955 0.65320624]
 [0.05389971 0.01459102 0.87052702]
 [0.02468172 0.85092403 0.43688403]]


In [25]:
d = np.random.randint(4, 15,size=(3,2))
print(d)

[[ 4 12]
 [ 5  9]
 [ 4  4]]


We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
with a mean of zero and a standard deviation of 0.1.
```
X = np.random.normal(0, 0.1, size=(1000,1000))
```

In [30]:
d = np.random.normal(2, .001, size=(10,4))
print(d)

[[1.99954117 1.99904383 2.00024853 2.00009989]
 [1.99873547 1.99888348 1.99879671 2.00136306]
 [1.99978651 1.9989953  2.00031625 1.99941583]
 [2.0003788  2.00043711 1.99900185 1.99945015]
 [1.99971858 2.00062351 1.99995068 1.99971604]
 [2.00065026 2.00029666 2.00061153 1.99966495]
 [1.99799136 1.99975597 1.9996667  1.99936744]
 [2.00036496 1.99906051 1.99937856 1.998412  ]
 [2.00084851 1.999949   1.99959136 1.9992558 ]
 [2.0004026  2.00125053 2.00001009 1.99881305]]


In [32]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
X[1,2] = 1000
print(X)

[[   1    2    3]
 [   4    5 1000]
 [   7    8    9]]


In [36]:
X = np.array([1,2,3,4,5])
print(X)
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
X = np.delete(X, [0,4])
print(X)

[1 2 3 4 5]
[2 3 4]


In [39]:
w = np.delete(Y, 0, axis=0)
print(Y)
print('-'*40)
print(w)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
[[4 5 6]
 [7 8 9]]


In [40]:
v = np.delete(Y, [0,2], axis=1)
print(Y)
print('-'*40)
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
[[2]
 [5]
 [8]]


In [41]:
v = np.append(X, [7,8])
print(X)
print('-'*40)
print(v)

[2 3 4]
----------------------------------------
[2 3 4 7 8]


In [43]:
v = np.append(Y, [[7,8,9]], axis=0)
print(Y)
print('-'*40)
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]


In [46]:
v = np.append(Y, [[4], [7], [10]], axis=1)
print(Y)
print('-'*40)
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [49]:
x = np.array([1, 2, 5, 6, 7])
y = np.array([[1,2,3],[7,8,9]])
z = np.insert(x,2,[3,4])
print(x)
print('-'*40)
print(z)


[1 2 5 6 7]
----------------------------------------
[1 2 3 4 5 6 7]


In [52]:
w = np.insert(y, 1, [4,5,6], axis=0)
print(y)
print('-'*40)
print(w)


[[1 2 3]
 [7 8 9]]
----------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
w = np.insert(y, 1, 5, axis=1)
print(y)
print('-'*40)
print(w)


[[1 2 3]
 [7 8 9]]
----------------------------------------
[[1 5 2 3]
 [7 5 8 9]]


In [54]:
w = np.insert(y, 1, 4, axis=0)
print(y)
print('-'*40)
print(w)

[[1 2 3]
 [7 8 9]]
----------------------------------------
[[1 2 3]
 [4 4 4]
 [7 8 9]]
